Algoritmo "ExercicioRetangulo"

Var

   base, altura, area, perimetro, diagonal : real
   
Inicio


   escreva("Base do retângulo: ")
   leia(base)
   escreva("Altura do retângulo: ")
   leia(altura)

   area <- base*altura
   perimetro <- (base+altura)*2
   diagonal <- RaizQ(base^2+altura^2)]
   
   escreval
   escreval("Área: ", area:6:4)
   escreval("Perímetro: ", perimetro:6:4)
   escreval("Diagonal: ", diagonal:6:4)

Fimalgoritmo